Add a prescan queue and limit the number of concurrent prescan processes in order to minimize the likelihood of resource exhaustion

diff --git a/scan_node/artemis-setup b/scan_node/artemis-setup
--- a/scan_node/artemis-setup
+++ b/scan_node/artemis-setup
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Title: artemis-setup
 # Description: Installation script for Artemis Network Traffic Virus Monitor
-# Version: 1.10
+# Version: 1.11
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,7 +18,7 @@
 #
 # Author: Andrew Withers (atw31337@gmail.com)
 
-VERSION=1.10
+VERSION=1.11
 
 usage ()
 {
@@ -54,6 +54,9 @@ VERSION=$VERSION
 
 # Maximum number of concurrent scan processes
 MAXPROC=$MAXPROC
+
+# Maximum number of PreScan processes
+MAXPRESCAN=$MAXPRESCAN
 
 # Maximum number of hashes to store in the hash cache file
 MAXHASH=$MAXHASH
@@ -160,6 +163,7 @@ else
 fi
 echo "Removing files..."
 [[ -f /usr/bin/artemis ]] && rm /usr/bin/artemis
+[[ -f /usr/bin/preScan ]] && rm /usr/bin/preScan
 [[ -f /usr/bin/orion ]] &&  rm /usr/bin/orion
 [[ -f /usr/bin/arteStat ]] && rm /usr/bin/arteStat
 [[ -f /usr/bin/arteLog ]] && rm /usr/bin/arteLog
@@ -298,11 +302,13 @@ fi
 
 # If non-interactive mode is selected, verify the integrity of the answer file and retrieve config variables.
 if [[ $MODE -eq 1 ]];then
-        if grep -q MYDOMAIN= "$AFILE" && grep -q RELAYHOST= "$AFILE" && grep -q MAXPROC= "$AFILE" && grep -q MAXHASH= "$AFILE" \
-        && grep -q IDIR= "$AFILE" && grep -q EMAIL= "$AFILE" && grep -q LOGSDATA= "$AFILE" && grep -q VTAPI= "$AFILE"; then
+        if grep -q MYDOMAIN= "$AFILE" && grep -q RELAYHOST= "$AFILE" && grep -q MAXPROC= "$AFILE" && grep -q MAXPRESCAN= "$AFILE" \
+	&& grep -q MAXHASH= "$AFILE" && grep -q IDIR= "$AFILE" && grep -q EMAIL= "$AFILE" && grep -q LOGSDATA= "$AFILE" \
+	&& grep -q VTAPI= "$AFILE"; then
                 MYDOMAIN=$(grep MYDOMAIN "$AFILE" | cut -d'=' -f2)
                 RELAYHOST=$(grep RELAYHOST "$AFILE" | cut -d'=' -f2)
                 MAXPROC=$(grep MAXPROC "$AFILE" | cut -d'=' -f2)
+		MAXPRESCAN=$(grep MAXPRESCAN "$AFILE" | cut -d'=' -f2)
                 MAXHASH=$(grep MAXHASH "$AFILE" | cut -d'=' -f2)
                 IDIR=$(grep IDIR "$AFILE" | cut -d'=' -f2)
                 EMAIL=$(grep EMAIL "$AFILE" | cut -d'=' -f2)
@@ -315,11 +321,20 @@ if [[ $MODE -eq 1 ]];then
         fi
 else	# If Interactive Mode is selected then acquire artemis.conf settings from the user
 	while ! [[ $MAXPROC =~ ^[1-9]+$ ]]; do
-                read -p 'Artemis: Enter the concurrent scan suppression threshold [4]: ' MAXPROC
+                read -p 'Artemis: Enter the maximum number of concurrent scan processes [4]: ' MAXPROC
                 if [[ -z $MAXPROC ]]; then
                         MAXPROC=4
                 fi
                 if ! [[ $MAXPROC =~ ^[1-9]+$ ]]; then
+                        echo "Invalid response. Try again."
+                fi
+        done
+	while ! [[ $MAXPRESCAN =~ ^[1-9]+$ ]]; do
+                read -p 'Artemis: Enter the maximum number of PreScan processes [15]: ' MAXPROC
+                if [[ -z $MAXPRESCAN ]]; then
+                        MAXPRESCAN=15
+                fi
+                if ! [[ $MAXPRESCAN =~ ^[1-9]+$ ]]; then
                         echo "Invalid response. Try again."
                 fi
         done
@@ -441,8 +456,10 @@ if [[ -z $(mysql --defaults-file=/etc/mysql/debian.cnf -BN -e "SHOW DATABASES LI
         mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "CREATE TABLE Logs (EntryID int NOT NULL AUTO_INCREMENT, DateTime DATETIME NOT NULL, SHA256 char(64) NOT NULL, \
                 MD5 char(32) NOT NULL, Scanned tinyint(1), Queued tinyint(1), Result tinyint(1), FileName varchar(255) NOT NULL, FileSize bigint NOT NULL, ScanTime float, QTime double, \
                 FileType varchar(5) NOT NULL, Source varchar(255), Destination varchar(255), PRIMARY KEY (EntryID)) ENGINE=InnoDB;"
-        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "CREATE TABLE Queue (FileID int NOT NULL AUTO_INCREMENT, FileName varchar(255) NOT NULL, TimeStamp DATETIME NOT NULL, \
+        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "CREATE TABLE ScanQueue (FileID int NOT NULL AUTO_INCREMENT, FileName varchar(255) NOT NULL, TimeStamp DATETIME NOT NULL, \
                 LogsID int NOT NULL, EntryTime double NOT NULL, PRIMARY KEY (FileID)) ENGINE=InnoDB;"
+	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "CREATE TABLE PreQueue (FileID int NOT NULL AUTO_INCREMENT, FileName varchar(255) NOT NULL, TimeStamp DATETIME NOT NULL, \
+		PRIMARY KEY (FileID)) ENGINE=InnoDB;"
 fi
 
 # Create a user group for the forwarder nodes
@@ -479,9 +496,9 @@ EOF
 
 EOF
 cp ./artemis-setup ../README ./scripts/parsOpts.sh /opt/artemis/
-cp ./scripts/artemis ./scripts/extract-cleanup ./scripts/artemis-logfile-cleanup ./scripts/artemis-brolog-cleanup  ./scripts/scavenger \
-./scripts/artemis-logRepair ./scripts/orion ./scripts/arteStat ./scripts/arteLog ./scripts/artemis-logstable-cleanup /usr/bin/
-cp ./scripts/artemisInit /usr/sbin/artemisInit
+cp ./scripts/artemis ./scripts/preScan ./scripts/extract-cleanup ./scripts/artemis-logfile-cleanup ./scripts/artemis-brolog-cleanup  \
+./scripts/scavenger ./scripts/artemis-logRepair ./scripts/orion ./scripts/arteStat ./scripts/arteLog ./scripts/artemis-logstable-cleanup /usr/bin/
+cp ./scripts/artemisInit /usr/sbin/
 
 cp ./conf/artemis /etc/cron.d/
 cp ./conf/artemis.service /lib/systemd/system/artemis.service
diff --git a/scan_node/scripts/artemis b/scan_node/scripts/artemis
--- a/scan_node/scripts/artemis
+++ b/scan_node/scripts/artemis
@@ -36,297 +36,120 @@ cat <<EOF
 Artemis Network Traffic Virus Monitor
 Usage: artemis [OPTION]
 
-	Options:
+        Options:
 
-		-h	   		This message
-		-v			Print version information
-		-f <file>		Force process a file
-		-p	    		Purge the hash cache
+                -h                      This message
+                -v                      Print version information
+                -f <file>               Force process a file
+                -p                      Purge the hash cache
 
 EOF
-}
-
-LogsEntry() {
-SIZE=$(du -b "$1" | awk '{print $1}')
-# If the filename contains a . then set the last extension as the filetype; otherwise make the filetype blank
-if echo "$4" | grep -q "\."; then
-	FILETYPE=$(echo "$4" | rev | cut -d'.' -f1 | rev)
-	if [[ ${#FILETYPE} -gt 5 ]]; then
-		FILETYPE=$(echo "$FILETYPE" | head -c5)
-	fi
-else
-	FILETYPE=""
-fi
-LOGSID=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO Logs (DateTime, SHA256, MD5, FileName, FileSize, FileType, \
-Source, Destination) VALUES ('$(date +%Y-%m-%d) $(date +%T)', '$2', '$3', '$4', $SIZE, '$FILETYPE', '$SOURCE', '$DEST'); SELECT LAST_INSERT_ID();")
-}
-
-sendAlert() {
-TFILE=$(mktemp -p /tmp/artemis/)	# Temporary file for alert email output
-VSIG=$(grep "$FILENAME" /var/log/virus-scan.log | cut -d' ' -f2)	# Virus signature from ClamScan output
-printf "From: %s\nTo: %s\nSubject: Malware Detected!\n\n" "$HOSTNAME" "$EMAIL"  > "$TFILE"
-printf "%s: %s has detected malware on the network.\n" "$TSTAMP" "$HOSTNAME" >> "$TFILE"
-if [[ -n $VSIG ]]; then
-	printf "Scan Result: %s\n" "$VSIG"
-fi
-printf "SHA256: %s\n" "$SHA256" >> "$TFILE"
-printf "MD5: %s\n" "$MD5" >> "$TFILE"
-if [[ -n $IDIR ]]; then
-	 printf "A copy of the infected file(s) can be located in %s\n" "$IDIR" >> "$TFILE"
-fi
-mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT FileName, Source, CONCAT('->') AS Arrow, Destination FROM Logs WHERE EntryID=$LOGSID;" >> "$TFILE"
-if [[ -e /opt/artemis/cache/$SHA256 ]]; then
-	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT FileName, Source, CONCAT('->') AS Arrow, Destination FROM Logs WHERE EntryID IN ($IDLIST);" >> "$TFILE"
-fi
-# VirusTotal analysis
-if [[ -n $VTAPI ]]; then
-	# Check if an analysis already exists
-	if [[ $(curl -sI https://www.virustotal.com/en/file/"$SHA256"/analysis/ | awk '/^HTTP/ {print $2}') -ne 200 ]]; then	# Analysis does not exist
-		# Upload file to VirusTotal for scanning
-		VTOUT=$(curl -s --request POST \
-			--url 'https://www.virustotal.com/vtapi/v2/file/scan' \
-			--form 'apikey='"$VTAPI" \
-			--form 'file=@'"$1")
-		# Check if the file was too large to be scanned via API
-                if echo "$VTOUT" | grep -q "Your client issued a request that was too large."; then
-                        VTLINK="The file was too large to be automatically scanned via API. Please upload the file manually."
-                else
-                        # Extract the scan results link from the output
-                        VTLINK=$(echo -n "$VTOUT" | cut -d',' -f6 | sed 's/\( "permalink": "\|"\)//g')
-                fi
-	else
-		# VT analysis already exists
-		VTLINK="https://www.virustotal.com/en/file/$SHA256/analysis/"
-	fi
-else
-	# VT File analysis page
-	VTLINK="https://www.virustotal.com/en/file/$SHA256/analysis/"
-fi
-printf "VirusTotal: %s\n" "$VTLINK" >> "$TFILE"
-sendmail -vt < "$TFILE"
-rm -f "$TFILE"
-}
-
-file_integrity_chk() {	 # checks and, if necessary, waits for a file to finish being written to disk
-local hash
-while [[ $(md5sum "$1" | cut -d' ' -f1) != "$hash" ]]; do
-	hash=$(md5sum "$1" | cut -d' ' -f1)
-	sleep 0.1
-done
-}
-
-getSrcDst() {
-# Check the current log
-if [[ -e /opt/artemis/logs/artemis-files.log ]]; then
-	SOURCE=$(grep "$FILENAME" /opt/artemis/logs/artemis-files.log | head -n1 | awk -F'[][]' '{print$2}' | sed 's/"//g')
-	DEST=$(grep "$FILENAME" /opt/artemis/logs/artemis-files.log | head -n1 | awk -F'[][]' '{print$4}' | sed 's/"//g')
-fi
-
-# If the Source/Destination are not located there, check the most recently archived log file
-if [[ -z $SOURCE ]] || [[ -z $DEST ]] && [[ -f /opt/artemis/logs/artemis-files.log.1.gz ]]; then
-	TEMPID=$(date +%s%N)
-	file_integrity_chk /opt/artemis/logs/artemis-files.log.1.gz # Ensure that the file has been completely written to disk during log rotation before proceeding
-	cp /opt/artemis/logs/artemis-files.log.1.gz /tmp/artemis/"$TEMPID".temp.gz
-	gzip -d /tmp/artemis/"$TEMPID".temp.gz
-	SOURCE=$(grep "$FILENAME" /tmp/artemis/"$TEMPID".temp | head -n1 | awk -F'[][]' '{print$2}' | sed 's/"//g')
-	DEST=$(grep "$FILENAME" /tmp/artemis/"$TEMPID".temp | head -n1 | awk -F'[][]' '{print$4}' | sed 's/"//g')
-	rm /tmp/artemis/"$TEMPID".temp
-fi
-
-# If the Source/Destination are not located in the archived log either, then wait for the data to be written to the current log
-if [[ -z $SOURCE ]] || [[ -z $DEST ]]; then
-	for (( i=0; i < 60; i++ )); do # For loop, rather than while, prevents infinite loops caused by log rotation
-		local counter=0
-		while ! [[ -e /opt/artemis/logs/artemis-files.log ]]; do       # Prevents missing file errors during log rotation
-				sleep 0.1
-				((counter++))
-				if [[ $counter -ge 300 ]]; then	# Prevents an inifinite while loop
-					break 2
-				fi
-		done
-		SOURCE=$(grep "$FILENAME" /opt/artemis/logs/artemis-files.log | head -n1 | awk -F'[][]' '{print$2}' | sed 's/"//g')
-		DEST=$(grep "$FILENAME" /opt/artemis/logs/artemis-files.log | head -n1 | awk -F'[][]' '{print$4}' | sed 's/"//g')
-		if [[ -z $SOURCE ]] || [[ -z $DEST ]]; then
-			sleep 1
-		else
-			break
-		fi
-	done
-fi
-}
-
-
-prescan() {
-TSTAMP="$(date +%Y-%m-%d) $(date +%T)"
-file_integrity_chk "$1"
-SHA256=$(sha256sum "$1" | cut -d' ' -f1)
-MD5=$(md5sum "$1" | cut -d' ' -f1)
-FILENAME=$(basename "$1")      # File name only
-getSrcDst
-LogsEntry "$1" "$SHA256" "$MD5" "$FILENAME"
-HASHID=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT HashID FROM Cache WHERE Hash='$SHA256' LIMIT 1;")
-if grep "$SOURCE" /opt/artemis/conf/blacklist | grep -vq "\#\|^$"; then		# Regex: Ignore comments and blank lines
-	# The source is present in the source blacklist
-	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=6 WHERE EntryID=$LOGSID;"
-	sendAlert "$1"
-	if [[ -n $IDIR ]]; then
-		mv "$DIR$FILENAME" "$IDIR$FILENAME"
-		chmod 600 "$IDIR$FILENAME"
-	fi
-elif grep "$SOURCE" /opt/artemis/conf/whitelist | grep -vq "\#\|^$"; then
-	# The source is present in the source whitelist
-	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=5 WHERE EntryID=$LOGSID;"
-elif grep "$SHA256\|$MD5" /opt/artemis/conf/blacklist | grep -vq "\#\|^$"; then
-        # The hash is present in the hash blacklist
-        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=4 WHERE EntryID=$LOGSID;"
-        sendAlert "$1"
-        if [[ -n $IDIR ]]; then
-                mv "$DIR$FILENAME" "$IDIR$FILENAME"
-                chmod 600 "$IDIR$FILENAME"
-        fi
-elif grep "$SHA256\|$MD5" /opt/artemis/conf/whitelist | grep -vq "\#\|^$"; then
-        # The hash is present in the hash whitelist
-        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=3 WHERE EntryID=$LOGSID;"
-elif [[ -n $HASHID ]] && [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Result FROM Cache WHERE Hash='$SHA256' LIMIT 1;") -ne 2 ]]; then
-	# Hash is present in the Cache table and the result was not an error
-	RESULT=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Result FROM Cache WHERE HashID=$HASHID;")
-	# Update the Logs and Cache table entries
-	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0 WHERE EntryID=$LOGSID;"
-	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Cache SET Hits=Hits+1, TimeStamp=$(date +%s%N) WHERE HashID=$HASHID;"
-	if [[ $RESULT == "NULL" ]]; then
-		echo "$LOGSID" >> /opt/artemis/cache/"$SHA256"
-	else    # Result is present in the Cache table
-		## Update the result in the Logs table
-		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Result=$RESULT WHERE EntryID=$LOGSID;"
-		if [[ $RESULT -eq 1 ]]; then
-			sendAlert "$1"
-			if [[ -n $IDIR ]]; then
-				mv "$DIR$FILENAME" "$IDIR$FILENAME"
-				chmod 600 "$IDIR$FILENAME"
-			fi
-		fi
-	fi
-else	# Hash does not exist in the Whitelist, Blacklist, or Cache tables
-	ENTRYTIME="$(date +%s).$(date +%N | head -c3)"
-	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "INSERT INTO Queue (FileName, TimeStamp, LogsID, EntryTime) VALUES ('$1', '$TSTAMP', $LOGSID, $ENTRYTIME);"
-	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Queued=1 WHERE EntryID=$LOGSID;"
-fi
 }
 
 exec 2>> /var/log/artemis.err
 
 # Got r00t?
 if [[ $(id -u) -ne 0 ]]; then
-	echo "Root privilege required. Try using sudo"
-	exit 0
+        echo "Root privilege required. Try using sudo"
+        exit 0
 fi
 
 # Check that the configuration file exists
 if [[ ! -f $CONF ]]; then
-	echo Artemis: Configuration file does nost exist!
-	exit 1
+        echo Artemis: Configuration file does nost exist!
+        exit 1
 fi
 
 # Parse options
 while [[ $OPTIND -lt $# ]];do
-	parsOpts "$@" "h,help,v,f:,p"
-	case $OPT in
-	h|help)
-		usage
-		exit 0
-		;;
-	v)
-		echo "Artemis Network Traffic Virus Monitor v$(grep VERSION /etc/artemis.conf | cut -d'=' -f2)"
-		exit 0
-		;;
-	f)
-		prescan "$OPTARG" &
-		exit 0
-		;;
-	p)
-		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "TRUNCATE TABLE Cache;" > /dev/null
-		echo "Artemis: Cache has been purged"
-		exit 0
-		;;
-	\?)
-		usage
-		exit 1
-		;;
-	:)
-		echo "Invalid number of arguments for option $OPTARG. $OPTARG requires $NUMARGS argument(s)."
-		exit 1
-		;;
-	esac
+        parsOpts "$@" "h,help,v,f:,p"
+        case $OPT in
+        h|help)
+                usage
+                exit 0
+                ;;
+        v)
+                echo "Artemis Network Traffic Virus Monitor v$(grep VERSION /etc/artemis.conf | cut -d'=' -f2)"
+                exit 0
+                ;;
+        f)
+                mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "INSERT INTO PreQueue (FileName, TimeStamp) VALUES \
+					('$OPTARG', '$(date +%Y-%m-%d) $(date +%T)');"
+                exit 0
+                ;;
+        p)
+                mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "TRUNCATE TABLE Cache;" > /dev/null
+                echo "Artemis: Cache has been purged"
+                exit 0
+                ;;
+        \?)
+                usage
+                exit 1
+                ;;
+        :)
+                echo "Invalid number of arguments for option $OPTARG. $OPTARG requires $NUMARGS argument(s)."
+                exit 1
+                ;;
+        esac
 done
 shift "$OPTIND"
 
-# Get variables from artemis.conf
-EMAIL=$(grep EMAIL "$CONF" | cut -d'=' -f2)
+# Get source directory from artemis.conf
 DIR=$(grep SDIR "$CONF" | cut -d'=' -f2)
-IDIR=$(grep IDIR "$CONF" | cut -d'=' -f2)
-MAXPROC=$(grep MAXPROC "$CONF" | cut -d'=' -f2)
-MAXHASH=$(grep MAXHASH "$CONF" | cut -d'=' -f2)
-VTAPI=$(grep VTAPI "$CONF" | cut -d'=' -f2)
 
-# Check that required variables contain values
-if [[ -z "$DIR" ]] || [[ -z "$MAXPROC" ]] || [[ -z "$MAXHASH" ]] || [[ -z "$EMAIL" ]]; then
-	echo Artemis: Invalid configuration detected! Check that the conf file has been properly configured.
-	exit 1
-fi
-
-# Create the infected file directory if it does not exist
-if [[ -n $IDIR ]]; then
-	if ! [[ -d $IDIR ]]; then
-		mkdir -pm 600 "$IDIR"
-	fi
+if [[ -z "$DIR" ]]; then
+		echo "Artemis: The source directory has not been properly configured in artemis.conf"
+		exit 1
 fi
 
 # Create a temporary file directory if it does not exist
-if ! [[ -d /tmp/artemis/ ]]; then
-	mkdir -m 660 /tmp/artemis/
-fi
+! [[ -d /tmp/artemis/ ]] && mkdir -m 660 /tmp/artemis/
 
 # Mount the cache directory
-if ! [[ -d /opt/artemis/cache/ ]]; then
-	mkdir -p /opt/artemis/cache/
-fi
+! [[ -d /opt/artemis/cache/ ]] && mkdir -p /opt/artemis/cache/
+
 if  ! mount | grep -q /opt/artemis/cache; then
-	mount -t tmpfs -o size=2m tmpfs /opt/artemis/cache/
-	chmod 600 /opt/artemis/cache/
+        mount -t tmpfs -o size=2m tmpfs /opt/artemis/cache/
+        chmod 600 /opt/artemis/cache/
 fi
 
-# Create a woker pid directory in the cache
+# Create a worker pid directory in the cache
 mkdir /opt/artemis/cache/workers/
+mkdir /opt/artemis/cache/prescans/
 
-# Truncate the Queue table. Ensures that the queue is emtpy at start up.
-mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "TRUNCATE TABLE Queue;"
+# Truncate the PreQueue and ScanQueue tables. Ensures that the queues are emtpy at start up.
+mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "TRUNCATE TABLE ScanQueue;"
+mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "TRUNCATE TABLE PreQueue;"
 
 # Start the Orion scanner
 /usr/bin/orion & ORIONPID=$!
+# Start the PreScanner
+/usr/bin/preScan & PRESCANPID=$!
 
 # Begin extraction directory monitoring
 inotifywait -q -m -e create,moved_to --format '%w%f' "$DIR" | while read FILE
 do
-	prescan "$FILE" &
+        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "INSERT INTO PreQueue (FileName, TimeStamp) VALUES \
+			('$FILE', '$(date +%Y-%m-%d) $(date +%T)');"
 done
 
-# Shutdown orion
+# Shutdown management processes
+kill -1 $PRESCANPID
 kill -1 $ORIONPID
 
 # Wait for orion to stop
+wait $PRESCANPID
 wait $ORIONPID
-
-# Kill any remaining child processes
-kill -9 "$(pgrep -x artemis | grep -v $$)" 2> /dev/null
 
 # Cleanup
 mount | grep /opt/artemis/cache && umount /opt/artemis/cache/
 [[ -d /opt/artemis/cache/ ]] && rm -rf /opt/artemis/cache/
 mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "DELETE FROM Logs WHERE Result IS NULL;"
 mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "DELETE FROM Cache WHERE Result IS NULL;"
-mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "TRUNCATE TABLE Queue;"
+mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "TRUNCATE TABLE ScanQueue;"
+mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e  "TRUNCATE TABLE PreQueue;"
 if [[ -d /tmp/artemis/ ]] && ! [[ -d /tmp/artemis/logRepair ]]; then
-	rm -rf /tmp/artemis/
+        rm -rf /tmp/artemis/
 fi
 
 exit
