Allow options to be specified in any order

diff --git a/scan_node/scripts/arteLog b/scan_node/scripts/arteLog
--- a/scan_node/scripts/arteLog
+++ b/scan_node/scripts/arteLog
@@ -26,7 +26,7 @@ cat <<EOF
 
 arteLog - Artemis log interface
 Usage: arteLog [Time OPTION]...[Query OPTION]
-If no Time option is selected or if it is placed after the Query option, the time period will default to the last 24 hours
+If no Time option is selected, then the time period will default to the last 24 hours
 
 	Time Period Options:
 		-D <YYYY-MM-HH>		Specific date
@@ -67,7 +67,7 @@ END=$(mysql --defaults-file=/etc/mysql/debian.cnf -BN -e "SELECT SYSDATE();")
 START=$(mysql --defaults-file=/etc/mysql/debian.cnf -BN -e "SELECT SUBDATE('$END', 1);")
 
 while [[ $OPTIND -lt $# ]]; do
-	parsOpts "$@" "h,help,D:,M:,Y:,H:,d:,w:,m:,y:,r:,i:,R:4,a,p,F:,e:,S:,T:,I:,f:"
+	parsOpts "$@" "h,help,D:,M:,Y:,H:,d:,w:,m:,y:,r:,i:,R:4,a"
 	case $OPT in
 	h|help)
 		usage
@@ -114,12 +114,22 @@ while [[ $OPTIND -lt $# ]]; do
 	a)
 		ALL=1
 		;;
+	 :)
+                echo "Invalid number of arguments for option $OPTARG. $OPTARG requires $NUMARGS argument(s)."
+                exit 1
+                ;;
+        esac
+done
+OPTIND=0
+while [[ $OPTIND -lt $# ]]; do
+        parsOpts "$@" "p,F:,e:,S:,T:,I:,f:"
+        case $OPT in
 	p)
-                		echo
-                		read -p 'Are you sure you want to delete all statistical data? This operation is irreversible. [y/N]: ' ANSWER
-                		if [[ $ANSWER == 'y' ]] || [[ $ANSWER == 'Y' ]]; then
-                        	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "TRUNCATE TABLE Logs;"
-                        	echo "vStat: All log data has been purged"
+                echo
+                read -p 'Are you sure you want to delete all statistical data? This operation is irreversible. [y/N]: ' ANSWER
+                if [[ $ANSWER == 'y' ]] || [[ $ANSWER == 'Y' ]]; then
+			mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "TRUNCATE TABLE Logs;"
+			echo "All log data has been purged"
                 fi
                 exit 0
                 ;;
@@ -190,14 +200,15 @@ while [[ $OPTIND -lt $# ]]; do
                 fi
                 ;;
         \?)
-                echo "Invalid option: $OPTARG"
-                exit 1
-                ;;
-        :)
+		if ! [[ $OPTARG =~ ^(h|help|D|M|Y|H|d|w|m|y|r|i|R|a)$ ]]; then
+			echo "Invalid option: $OPTARG"
+			exit 1
+		fi
+		;;
+	:)
                 echo "Invalid number of arguments for option $OPTARG. $OPTARG requires $NUMARGS argument(s)."
                 exit 1
                 ;;
 	esac
-
 done
 
