Add the capability to whitelist and blacklist source IPs

diff --git a/scan_node/scripts/artemis b/scan_node/scripts/artemis
--- a/scan_node/scripts/artemis
+++ b/scan_node/scripts/artemis
@@ -43,6 +43,8 @@ Usage: artemis [OPTION]
 		-v			Print version information
 		-f <file>		Force process a file
 		-p	    		Purge the hash cache
+		-s <Source IPv4>	Add a source IP to the whitelist
+		-o <Source IPv4>	Add a source IP to the blacklist
 		-w <Hash>		Add a SHA256 or MD5 hash to the whitelist
 		-b <Hash>		Add a SHA256 or MD5 hash to the blacklist
 
@@ -60,14 +62,14 @@ if echo "$4" | grep -q "\."; then
 else
 	FILETYPE=""
 fi
-LOGSID=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO Logs (DateTime, SHA256, MD5, FileName, FileSize, FileType) \
-VALUES ('$(date +%Y-%m-%d) $(date +%T)', '$2', '$3', '$4', $SIZE, '$FILETYPE'); SELECT LAST_INSERT_ID();")
+LOGSID=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO Logs (DateTime, SHA256, MD5, FileName, FileSize, FileType, \
+Source, Destination) VALUES ('$(date +%Y-%m-%d) $(date +%T)', '$2', '$3', '$4', $SIZE, '$FILETYPE', '$SOURCE', '$DEST'); SELECT LAST_INSERT_ID();")
 }
 
 sendAlert() {
 TFILE=$(mktemp -p /tmp/artemis/)	# Temporary file for alert email output
 printf "From: %s\nTo: %s\nSubject: Malware Detected!\n\n" "$HOSTNAME" "$EMAIL"  > "$TFILE"
-printf "%s: %s has detected malware on the network.\n " "$TSTAMP" "$HOSTNAME" >> "$TFILE"
+printf "%s: %s has detected malware on the network.\n" "$TSTAMP" "$HOSTNAME" >> "$TFILE"
 printf "SHA256: %s\n" "$SHA256" >> "$TFILE"
 printf "MD5: %s\n" "$MD5" >> "$TFILE"
 if [[ -n $IDIR ]]; then
@@ -80,7 +82,7 @@ fi
 # VirusTotal analysis
 if [[ -n $VTAPI ]]; then
 	# Check if an analysis already exists
-	if [[ $(curl -sI https://www.virustotal.com/en/file/$SHA256/analysis/ | awk '/^http/ {print $2}') -ne 200 ]]; then	# Analysis does not exist
+	if [[ $(curl -sI https://www.virustotal.com/en/file/"$SHA256"/analysis/ | awk '/^http/ {print $2}') -ne 200 ]]; then	# Analysis does not exist
 		# Upload file to VirusTotal for scanning
 		VTOUT=$(curl -s --request POST \
 			--url 'https://www.virustotal.com/vtapi/v2/file/scan' \
@@ -129,7 +131,7 @@ fi
 
 # If the Source/Destination are not located in the archived log either, then wait for the data to be written to the current log
 if [[ -z $SOURCE ]] || [[ -z $DEST ]]; then
-        for (( i=0; i < 300; i++ )); do # For loop prevents infinite loops caused by log rotation
+        for (( i=0; i < 300; i++ )); do # For loop, rather than while, prevents infinite loops caused by log rotation
                 local counter=0
 		while ! [[ -e /opt/artemis/logs/artemis-files.log ]]; do       # Prevents missing file errors during log rotation
                                 sleep 0.1
@@ -156,16 +158,14 @@ file_integrity_chk "$1"
 SHA256=$(sha256sum "$1" | cut -d' ' -f1)
 MD5=$(md5sum "$1" | cut -d' ' -f1)
 FILENAME=$(basename "$1")      # File name only
+getSrcDst
 LogsEntry "$1" "$SHA256" "$MD5" "$FILENAME"
 HASHID=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT HashID FROM Cache WHERE Hash='$SHA256' LIMIT 1;")
-if [[ -n $HASHID ]] && [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Result FROM Cache WHERE Hash='$SHA256' LIMIT 1;") -ne 2 ]]; then 
-# Hash is present in the Cache table and the result was not an error
-	SCANNED=0
-        QUEUED=0
-        getSrcDst
-        RESULT=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Result FROM Cache WHERE HashID=$HASHID;")
+if [[ -n $HASHID ]] && [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Result FROM Cache WHERE Hash='$SHA256' LIMIT 1;") -ne 2 ]]; then
+	# Hash is present in the Cache table and the result was not an error
+	RESULT=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Result FROM Cache WHERE HashID=$HASHID;")
         # Update the Logs and Cache table entries
-        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=$SCANNED, Queued=$QUEUED, Source='$SOURCE', Destination='$DEST' WHERE EntryID=$LOGSID;"
+        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0 WHERE EntryID=$LOGSID;"
         mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Cache SET Hits=Hits+1, TimeStamp=$(date +%s%N) WHERE HashID=$HASHID;"
         if [[ $RESULT == "NULL" ]]; then
                 echo "$LOGSID" >> /opt/artemis/cache/"$SHA256"
@@ -180,24 +180,34 @@ if [[ -n $HASHID ]] && [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artem
                         fi
                 fi
         fi
-elif [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM Blacklist WHERE MD5='$MD5';") -ne 0 ]] ||\
-	[[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM Blacklist WHERE SHA256='$SHA256';") -ne 0 ]]; then # Compare the hashes against the blacklist
-	getSrcDst
-	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=4, Source='$SOURCE', Destination='$DEST' WHERE EntryID=$LOGSID;"
+elif [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM SourceBlacklist WHERE Source='$SOURCE';") -gt 0 ]]; then
+	# The source is present in the source blacklist
+	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=6 WHERE EntryID=$LOGSID;"
+	sendAlert "$1"
+	if [[ -n $IDIR ]]; then
+		mv "$DIR$FILENAME" "$IDIR$FILENAME"
+		chmod 600 "$IDIR$FILENAME"
+	fi
+elif [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM SourceWhitelist WHERE Source='$SOURCE';") -gt 0 ]]; then
+	# The source is presnet in the source whitelist
+	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=5 WHERE EntryID=$LOGSID;"
+elif [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM HashBlacklist WHERE MD5='$MD5';") -gt 0 ]] ||\
+	[[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM HashBlacklist WHERE SHA256='$SHA256';") -gt 0 ]]; then
+	# The hash is present in the hash blacklist
+	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=4 WHERE EntryID=$LOGSID;"
 	sendAlert "$1"
 	if [[ -n $IDIR ]]; then
                	mv "$DIR$FILENAME" "$IDIR$FILENAME"
                	chmod 600 "$IDIR$FILENAME"
 	fi
-	elif [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM Whitelist WHERE MD5='$MD5';") -ne 0 ]] ||\
-	[[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM Whitelist WHERE SHA256='$SHA256';") -ne 0 ]]; then   # Compare the hashes against the whitelist
-	getSrcDst
-        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=3, Source='$SOURCE', Destination='$DEST' WHERE EntryID=$LOGSID;"
+elif [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM HashWhitelist WHERE MD5='$MD5';") -gt 0 ]] ||\
+	[[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM HashWhitelist WHERE SHA256='$SHA256';") -gt 0 ]]; then
+	# The hash is present in the hash whitelist
+	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=3 WHERE EntryID=$LOGSID;"
 else	# Hash does not exist in the Cache Table or Whitelist/Blacklist
-	QUEUED=1
 	ENTRYTIME="$(date +%s).$(date +%N | head -c3)"
 	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "INSERT INTO Queue (FileName, TimeStamp, LogsID, EntryTime) VALUES ('$1', '$TSTAMP', $LOGSID, $ENTRYTIME);"
-	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Queued=$QUEUED WHERE EntryID=$LOGSID;"
+	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Queued=1 WHERE EntryID=$LOGSID;"
 fi
 }
 
@@ -217,7 +227,7 @@ fi
 
 # Parse options
 while [[ $OPTIND -lt $# ]];do
-	parsOpts "$@" "h,help,v,f:,p,w:,b:"
+	parsOpts "$@" "h,help,v,f:,p,s:,o:,w:,b:"
 	case $OPT in
 	h|help)
 		usage
@@ -236,33 +246,71 @@ while [[ $OPTIND -lt $# ]];do
 		echo "Artemis: Cache has been purged"
 		exit 0
 		;;
-	w)
-		if [[ $(echo -n $OPTARG | wc -c) -eq 32 ]]; then 	# MD5
-			if [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM Whitelist WHERE MD5='$OPTARG';") -eq 0 ]]; then
-				mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO Whitelist (MD5) VALUES ('$OPTARG');"
+	s)
+		if [[ $(echo -n "$OPTARG" | wc -c) -le 15 ]]; then
+			if [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM SourceWhitelist WHERE Source='$OPTARG';") -eq 0 ]]; then
+				mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "INSERT INTO SourceWhitelist (Source) VALUES ('$OPTARG');"
+				echo "$OPTARG has been added to the whitelist"
+			else
+				echo "$OPTARG already exists in the whitelist"
 			fi
-		elif [[ $(echo -n $OPTARG | wc -c) -eq 64 ]]; then # SHA256
-			if [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM Whitelist WHERE SHA256='$OPTARG';") -eq 0 ]]; then
-				mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO Whitelist (SHA256) VALUES ('$OPTARG');"
+			exit 0
+		else
+			echo "Invalid IPv4 address"
+			exit 1
+		fi
+		;;
+	o)
+		if [[ $(echo -n  "$OPTARG" | wc -c) -le 15 ]]; then
+			if [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM SourceBlacklist WHERE Source='$OPTARG';") -eq 0 ]]; then
+				mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "INSERT INTO SourceBlacklist (Source) VALUES ('$OPTARG');"
+				echo "$OPTARG has been added to the blacklist"
+			else
+				echo "$OPTARG already exists in the blacklist"
+			fi
+			exit 0
+		else
+			echo "Invalid IPv4 address"
+			exit 1
+		fi
+		;;
+	w)
+		if [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM HashWhitelist WHERE MD5='$OPTARG' OR SHA256='$OPTARG';") -eq 0 ]]; then
+			if [[ $(echo -n "$OPTARG" | wc -c) -eq 32 ]]; then 	# MD5
+				mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO HashWhitelist (MD5) VALUES ('$OPTARG');"
+				echo "$OPTARG has been added to the whitelist"
+				exit 0
+			elif [[ $(echo -n "$OPTARG" | wc -c) -eq 64 ]]; then # SHA256
+				mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO HashWhitelist (SHA256) VALUES ('$OPTARG');"
+				echo "$OPTARG has been added to the whitelist"
+				exit 0
+			else
+				echo "Invalid hash value"
+				exit 1
 			fi
 		else
-			echo "Invalid hash value"
+			echo "$OPTARG already exists in the whitelist"
+			exit 1
 		fi
-		exit 0
 		;;
 	b)
-		if [[ $(echo -n $OPTARG | wc -c) -eq 32 ]]; then	# MD5
-			if [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM Blacklist WHERE MD5='$OPTARG';") -eq 0 ]]; then
-				mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO Blacklist (MD5) VALUES ('$OPTARG');"
-			fi
-		elif [[ $(echo -n $OPTARG | wc -c) -eq 64 ]]; then # SHA256
-			if [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM Blacklist WHERE SHA256='$OPTARG';") -eq 0 ]]; then
-				mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO Blacklist (SHA256) VALUES ('$OPTARG');"
+		if [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM HashBlacklist WHERE MD5='$OPTARG' OR SHA256='$OPTARG';") -eq 0 ]]; then
+			if [[ $(echo -n "$OPTARG" | wc -c) -eq 32 ]]; then	# MD5
+				mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO HashBlacklist (MD5) VALUES ('$OPTARG');"
+				echo "$OPTARG has been added to the blacklist"
+				exit 0
+			elif [[ $(echo -n "$OPTARG" | wc -c) -eq 64 ]]; then # SHA256
+				mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO HashBlacklist (SHA256) VALUES ('$OPTARG');"
+				echo "$OPTARG has been added to the blacklist"
+				exit 0
+			else
+				echo "Invalid hash value"
+				exit 1
 			fi
 		else
-			echo "Invalid hash value"
+			echo "$OPTARG already exists in the blacklist"
+			exit 1
 		fi
-		exit 0
 		;;
 	\?)
 		usage
