The -e condition encapsulating the filescan function was causing issues with scans being drop and worker slots not being reopened

diff --git a/scan_node/scripts/orion b/scan_node/scripts/orion
--- a/scan_node/scripts/orion
+++ b/scan_node/scripts/orion
@@ -93,108 +93,105 @@ fi
 }
 
 filescan() {
-if [[ -e $1 ]]; then
-	HASH=$(sha256sum "$1" | awk '{ print $1 }')
-	FILENAME=$(basename "$1") # File name only
-	EXITTIME="$(date +%s).$(date +%N | head -c3)"
-	QTIME=$(echo "scale=3; $EXITTIME - $ENTRYTIME" | bc)
-	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET QTime=$QTIME WHERE EntryID=$LOGSID;"
-	HASHID=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT HashID FROM Cache WHERE Hash='$HASH' LIMIT 1;")
-	if [[ -z $HASHID ]]; then	# Hash does not exist in the Cache Table
-		HASHID=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO Cache (Hash, Hits, TimeStamp) VALUES ('$HASH', 1, $(date +%s%N)); SELECT LAST_INSERT_ID();")
-		SCANNED=1
-		TLOG=$(mktemp -p /tmp/artemis/)  # Temporary storage for log output
-		date > "$TLOG"
-		clamscan "$1" >> "$TLOG"
-		RESULT=$?
-		# Add the result of the scan to the Cache table
-		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Cache SET Result=$RESULT WHERE HashID=$HASHID;"
-		# Release the worker slot in the workers pid directory
-		rm /opt/artemis/cache/workers/$BASHPID.pid
-		SCANTIME=$(grep Time "$TLOG" | awk '{print $2}')
-		getSrcDst
-		# Update the Logs table with the data from the scanned file
-                mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=$SCANNED, Result=$RESULT, ScanTime=$SCANTIME, \
-                Source='$SOURCE', Destination='$DEST' WHERE EntryID=$LOGSID;"
-                # If a duplicate hash file exists add the result to the Logs entries contained in the file
-                if [[ -e /opt/artemis/cache/$HASH ]]; then
-                	# Find number of LogsIDs listed in the duplicate hash file
-			NUMIDS=$(wc -l < "/opt/artemis/cache/$HASH")
-			if  [[ $NUMIDS -gt 1 ]]; then
-				# Create an EntryID list to be used in queries
-                        	while read LINE; do
-                        		if [[ -z $IDLIST ]]; then
-                                		IDLIST="$LINE"
-                                	else
-                                		IDLIST+=",$LINE"
-                                	fi
-                        	done </opt/artemis/cache/"$HASH"
-                        	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Result=$RESULT WHERE EntryID IN ($IDLIST);"
-			else
-				mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Result=$RESULT WHERE EntryID=$(cat /opt/artemis/cache/$HASH);"
-			fi
-                fi
-		if [[ $RESULT -eq 1 ]]; then    #An exit code of 1 indicates that an infection has been detected.
-			# If Artemis has been configured to move infected files then move the file to the appropriate directory
+HASH=$(sha256sum "$1" | awk '{ print $1 }')
+FILENAME=$(basename "$1") # File name only
+EXITTIME="$(date +%s).$(date +%N | head -c3)"
+QTIME=$(echo "scale=3; $EXITTIME - $ENTRYTIME" | bc)
+mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET QTime=$QTIME WHERE EntryID=$LOGSID;"
+HASHID=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT HashID FROM Cache WHERE Hash='$HASH' LIMIT 1;")
+if [[ -z $HASHID ]]; then	# Hash does not exist in the Cache Table
+	HASHID=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO Cache (Hash, Hits, TimeStamp) VALUES ('$HASH', 1, $(date +%s%N)); SELECT LAST_INSERT_ID();")
+	SCANNED=1
+	TLOG=$(mktemp -p /tmp/artemis/)  # Temporary storage for log output
+	date > "$TLOG"
+	clamscan "$1" >> "$TLOG"
+	RESULT=$?
+	# Add the result of the scan to the Cache table
+	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Cache SET Result=$RESULT WHERE HashID=$HASHID;"
+	# Release the worker slot in the workers pid directory
+	rm /opt/artemis/cache/workers/$BASHPID.pid
+	SCANTIME=$(grep Time "$TLOG" | awk '{print $2}')
+	getSrcDst
+	# Update the Logs table with the data from the scanned file
+        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=$SCANNED, Result=$RESULT, ScanTime=$SCANTIME, \
+        Source='$SOURCE', Destination='$DEST' WHERE EntryID=$LOGSID;"
+        # If a duplicate hash file exists add the result to the Logs entries contained in the file
+        if [[ -e /opt/artemis/cache/$HASH ]]; then
+        	# Find number of LogsIDs listed in the duplicate hash file
+		NUMIDS=$(wc -l < "/opt/artemis/cache/$HASH")
+		if  [[ $NUMIDS -gt 1 ]]; then
+			# Create an EntryID list to be used in queries
+                        while read LINE; do
+                        	if [[ -z $IDLIST ]]; then
+                               		IDLIST="$LINE"
+                               	else
+                               		IDLIST+=",$LINE"
+                               	fi
+                        done </opt/artemis/cache/"$HASH"
+                        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Result=$RESULT WHERE EntryID IN ($IDLIST);"
+		else
+			mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Result=$RESULT WHERE EntryID=$(cat /opt/artemis/cache/$HASH);"
+		fi
+	fi
+	if [[ $RESULT -eq 1 ]]; then    #An exit code of 1 indicates that an infection has been detected.
+		# If Artemis has been configured to move infected files then move the file to the appropriate directory
+		if [[ -n $IDIR ]]; then
+			if [[ -e /opt/artemis/cache/$HASH ]]; then
+                               	# Move each copy of the infected file to the appropriate directory
+                               	while read LINE; do
+                                       	IFILE=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT FileName FROM Logs WHERE EntryID=$$LINE;")
+                                        mv "$DIR$IFILE" "$IDIR$IFILE"
+                                        chmod 600 "$IDIR$IFILE"
+                                done </opt/artemis/cache/"$HASH"
+                        fi
+                        mv "$1" "$IDIR$FILENAME"
+                        chmod 600 "$IDIR$FILENAME"
+		fi
+		sendAlert
+	fi
+	if [[ -e /opt/artemis/cache/$HASH ]]; then
+               	rm /opt/artemis/cache/"$HASH"
+        fi
+	printf "SHA256: %s\n" "$HASH" >> "$TLOG"
+	printf "Received: %s\n\n" "$TSTAMP" >> "$TLOG"
+	cat "$TLOG" >> /var/log/virus-scan.log
+	rm  "$TLOG"
+	# Cache table maintenance
+	# Remove any existing duplicate hashes
+	DUPHASH=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Hash FROM Cache GROUP BY Hash HAVING COUNT(*) > 1 LIMIT 1;")
+        while [[ -n $DUPHASH ]]; do
+		DEL=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT HashID FROM Cache WHERE Hash='$DUPHASH' LIMIT 1;")
+		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "DELETE FROM Cache WHERE HashID=$DEL;"
+                DUPHASH=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Hash FROM Cache GROUP BY Hash HAVING COUNT(*) > 1 LIMIT 1;")
+	done
+	# Remove entries that contain an error result.
+        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "DELETE FROM Cache WHERE Result=2;"
+	# If the cache is larger than the max cache size, delete hashes based on the greatest time interval since last hit
+	while [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM Cache;") -gt $MAXHASH ]]; do
+		DEL=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT HashID FROM Cache ORDER BY TimeStamp ASC LIMIT 1;")
+		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "DELETE FROM Cache WHERE HashID=$DEL;"
+	done
+else	# Hash is present in the Cache table
+	# Release the worker slot in the workers pid directory
+	rm /opt/artemis/cache/workers/$BASHPID.pid
+	SCANNED=0
+	getSrcDst
+	# Update the Logs and Cache table entries
+	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=$SCANNED, Source='$SOURCE', Destination='$DEST' WHERE EntryID=$LOGSID;"
+        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Cache SET Hits=Hits+1, TimeStamp=$(date +%s%N) WHERE HashID=$HASHID;"
+	# Get the result from the Cache table
+	RESULT=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Result FROM Cache WHERE HashID=$HASHID;")
+	if [[ $RESULT == "NULL" ]]; then
+		echo "$LOGSID" >> /opt/artemis/cache/"$HASH"
+	else	# Result is present in the Cache table
+		# Update the result in the Logs table
+		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Result=$RESULT WHERE EntryID=$LOGSID;"
+		if [[ $RESULT -eq 1 ]]; then
 			if [[ -n $IDIR ]]; then
-				if [[ -e /opt/artemis/cache/$HASH ]]; then
-                                	# Move each copy of the infected file to the appropriate directory
-                                	while read LINE; do
-                                        	IFILE=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT FileName FROM Logs WHERE EntryID=$$LINE;")
-                                               	mv "$DIR$IFILE" "$IDIR$IFILE"
-                                               	chmod 600 "$IDIR$IFILE"
-                                        done </opt/artemis/cache/"$HASH"
-                                fi
-                                mv "$1" "$IDIR$FILENAME"
-                                chmod 600 "$IDIR$FILENAME"
+				mv "$DIR$FILENAME" "$IDIR$FILENAME"
+				chmod 600 "$IDIR$FILENAME"
 			fi
 			sendAlert
-		fi
-		if [[ -e /opt/artemis/cache/$HASH ]]; then
-                	rm /opt/artemis/cache/"$HASH"
-                fi
-		printf "SHA256: %s\n" "$HASH" >> "$TLOG"
-		printf "Received: %s\n\n" "$TSTAMP" >> "$TLOG"
-		cat "$TLOG" >> /var/log/virus-scan.log
-		rm  "$TLOG"
-		# Cache table maintenance
-		# Remove any existing duplicate hashes
-		DUPHASH=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Hash FROM Cache GROUP BY Hash HAVING COUNT(*) > 1 LIMIT 1;")
-                while [[ -n $DUPHASH ]]; do
-			DEL=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT HashID FROM Cache WHERE Hash='$DUPHASH' LIMIT 1;")
-			mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "DELETE FROM Cache WHERE HashID=$DEL;"
-                        DUPHASH=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Hash FROM Cache GROUP BY Hash HAVING COUNT(*) > 1 LIMIT 1;")
-		done
-		# Remove entries that contain an error result.
-                        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "DELETE FROM Cache WHERE Result=2;"
-		# If the cache is larger than the max cache size, delete hashes based on the greatest time interval since last hit
-		while [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM Cache;") -gt $MAXHASH ]]; do
-			DEL=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT HashID FROM Cache ORDER BY TimeStamp ASC LIMIT 1;")
-			mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "DELETE FROM Cache WHERE HashID=$DEL;"
-		done
-	else	# Hash is present in the Cache table
-		# Release the worker slot in the workers pid directory
-		rm /opt/artemis/cache/workers/$BASHPID.pid
-		SCANNED=0
-		getSrcDst
-		# Update the Logs and Cache table entries
-		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=$SCANNED, Source='$SOURCE', Destination='$DEST' WHERE EntryID=$LOGSID;"
-                mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Cache SET Hits=Hits+1, TimeStamp=$(date +%s%N) WHERE HashID=$HASHID;"
-		# Get the result from the Cache table
-		RESULT=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Result FROM Cache WHERE HashID=$HASHID;")
-		if [[ $RESULT == "NULL" ]]; then
-			echo "$LOGSID" >> /opt/artemis/cache/"$HASH"
-		else	# Result is present in the Cache table
-
-			# Update the result in the Logs table
-			mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Result=$RESULT WHERE EntryID=$LOGSID;"
-			if [[ $RESULT -eq 1 ]]; then
-				if [[ -n $IDIR ]]; then
-					mv "$DIR$FILENAME" "$IDIR$FILENAME"
-					chmod 600 "$IDIR$FILENAME"
-				fi
-				sendAlert
-			fi
 		fi
 	fi
 fi
